/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tteoubgogwrjorsybuyd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZW91YmdvZ3dyam9yc3lidXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDk4MjksImV4cCI6MjA3NzIyNTgyOX0.4nCYO2j-8gKOdB-_XZfqY3Lb0Gl0UdjDQ7pnP8fp4LQ"